import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Container, Theme } from "@radix-ui/themes";
import { Header } from "./components/Core/Header/Header";
import { SideNavigation } from "./components/Core/SideNavigation/SideNavigation";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./providers";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      staleTime: 30000,
      refetchOnWindowFocus: false,
    },
  },
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <Theme
            appearance="dark"
            accentColor="indigo"
            grayColor="sand"
            radius="large"
            scaling="95%"
            className="flex flex-col"
            panelBackground="translucent"
          >
            <Providers>
              <Header />
              <section className="flex flex-col items-start grow">
                <div className="grow w-full p-6">{children}</div>
                <div className="w-full flex justify-center py-4">
                  <SideNavigation />
                </div>
              </section>
            </Providers>
          </Theme>
        </main>
      </body>
    </html>
  );
}
